#CodeAssist project settings
#Sat Oct 03 19:26:57 GMT+03:00 2026
tree.expanded.Project=root\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/src/main/kotlin\ndir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/src/main/res/drawable\ndir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/src/main/res/values\ndir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/build/outputs/apk
module\:app
build-outputs\:app
root\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/src/main/res
dir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/src/main/res/mipmap
dir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/build/outputs/apk/debug
workspace
dir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/wedora/app/src/main/res/mipmap-anydpi-v26
